### ISSUE TITLE
Non-performant use of fibers on Windows

### ISSUE THREAD

**Issue by jesta88** [google/marl#12]
https://github.com/google/marl/blob/8c98371e534c1f4fc0faaa91575027d13ab74f54/src/osfiber_windows.h#L67

The Win32 `CreateFiber` function has unexpected virtual memory size by default. When using `CreateFiberEx`, default behavior is to round stack size to next multiple of 1MiB. With `CreateFiber`, for some reason it rounds to 2MiB, which is even worse. 

Now even if you use `CreateFiberEx`, there's still some weirdness. If `dwStackCommitSize` and `dwStackReserveSize` are equal, the stack size will still round to 1MiB. The only way is to use it like this: 
`CreateFiberEx(size - 1, size, FIBER_FLAG_FLOAT_SWITCH, cb, NULL);`

Note that even then, the stack can't be less than `dwAllocationGranularity`, which is typically 64KiB. If this minimum stack size is OK for performance, then that's how fiber creation should be done on Windows.

If we need smaller values (16KiB is common in schedulers), then asm fibers should be used instead IMO.

**Comment by ben-clayton** [comment]
Thank you for your feedback @jesta88.

> The Win32 CreateFiber function has unexpected virtual memory size by default. When using CreateFiberEx, default behavior is to round stack size to next multiple of 1MB. With CreateFiber, for some reason it rounds to 2MB, which is even worse.

My understanding was that this is an initial reservation size, not a committed size. For Win64, this seems like a non-issue? For 32-bit, I can see why this would be problematic.

Am I missing something?

One of my colleagues (@AWoloszyn) has some previous experience writing a fiber context switch in Windows, and advised against it due to complexities with implementation (he can give more information). If the fiber stack size is a deal breaker for windows, I'd be open to making changes here (or accepting PRs).

Currently marl has [a fixed stack size of 1 meg](https://github.com/google/marl/blob/master/include/marl/scheduler.h#L136) per fiber (non-windows), which is larger than I'd like, but does make things fairly consistent across the different platforms. I do intend to make this configurable and to lower the default value down significantly.

Many thanks,
Ben

**Comment by jesta88** [comment]
It's not just a reservation size unfortunately. See this simple test: https://gist.github.com/SergeyMakeev/65b8b3ee72c65b2a70534cd873e540f6

Results:
> estimated : 78.125000 Mb
> reality : 5007.000000 Mb
> 
> estimated : 16384 bytes
> reality : 1050044 bytes

It's a known quirk of Win32 fibers, and the workaround I mentioned has been battle-tested in production for quite a while. See the Ruby implementation: https://github.com/ruby/ruby/commit/c462c50d6336a0c7823ff8cfce51f8bff22eeff6#diff-d6ef5d5c0939813bfb4ff4bdab9f3930R574

For now since your stack size is hard-coded to 1MiB it won't make a huge difference, but eventually if you support configurable stack sizes, you could see non-trivial gains.

**Comment by ben-clayton** [comment]
I believe the original request has been fixed with https://github.com/google/marl/pull/173.
It still might be beneficial to have a non-Win32-Fiber (assembly) implementation at some point, but that goes beyond the scope of this issue.
Closing.
