### ISSUE TITLE
thread affinity support for *nix systems

### ISSUE THREAD

**Issue by magenbluten** [google/marl#136]
do you have plans to support thread pinning of the worker threads like in the windows implementation?

it would be nice if a "user" of `marl` could define some sort of `affinity-policy` to be able to adjust to requirements ( e.g. single thread pinning vs pinning to group of threads together ).

thinking of pseudo++ code:

```cpp

// we might have 4 workers pinned to 2 compute cores
// in any case, we have to use cores `1` and `2`
auto allowedCpusFromSomewhere( int workerId ) { return marl::CpuSet{1, 2 }; };

main() {
  ...
  marl::Scheduler scheduler;
  scheduler.bind();
  //scheduler.setWorkerThreadCount(4);
  scheduler.setWorkerThreadCountWithAffinity(
    4, []( auto const workerId, auto const& nativeHandle ) noexcept {
      marl::AffinityPolicy.pin( nativeHandle, allowedCpusFromSomewhere(workerId) );
      // Or
      nativeHandle.pin(CpuSet{1,2,3,4});
      // Or
  }
  // Or
  scheduler.setWorkerThreadCountWithAffinity(marl::ForAll{marl::CpuSet{1,2,3,4}});
  scheduler.setWorkerThreadCountWithAffinity(marl::OneOf{marl::CpuSet{1,2,3,4}});
  ...
}
```

furthermore, a user might just want to specify exactly which cpu cores are allowed to be used due to "external" requirements (thinking of network card capture into worker queue. the capture threads a pinned to single threads and these threads must be different to `marl`s native worker threads).

would that make any sense?

( yes i looked into `src/thread.cc` and read the comment claiming that pinning to a group is favourable instead of pinning to single thread. however, i guess it could be 
application dependent, why not let the user decide instead of hardcoding? )

anyhow, on *nix no pinning at all.

**Comment by ben-clayton** [comment]
Hi @magenbluten,

So I initially experimented with thread affinities on ubuntu and macOS with the goal of ensuring each worker was pinned to each core. Benchmarking, however, clearly suggested that this was a significant performance loss when doing this. I suspected that the rest of the applications running in the background were then forcefully interrupting the worker threads, when unpinning allows some shuffle room as marl workers context switch. I have no proof for this though, and I'm no macOS / linux thread scheduler expert. 

The reason Windows gets special treatment is that it's the only way I've found to actually use more than 64 logical cores. I'm fortunate enough to own a 3990x, and this was required to use more than half its processing power.

While somewhat kludgy, you may be able to set your thread affinities with the existing [`marl::Scheduler::setThreadInitializer()`](https://github.com/google/marl/blob/c716869a764621316d0c25086a14537444214569/include/marl/scheduler.h#L80) method. This is called for each worker thread that's spawned, and you could make your own thread affinity pinning calls from there. Unfortunately, the callback does not include the worker id, so you'd either have to have an external counter captured-by-ref, or do something filthy with `std::this_thread`.

That said, I do like the direction of your proposal. Some thoughts:

Instead of `nativeHandle` or `marl::AffinityPolicy`, I'd probably put this info into `marl::Thread::Affinity` or somewhere similar, and then have this as a constructor to `marl::Thread`. I could imagine something like:

```c++
class Thread {
public:
    struct Affinity {
        // Core identifies a logical processor unit.
        struct Core { /* TBD: Likely OS / platform dependent */ };

        // Policy is a function that returns an Affinity for the given worker by id.
        using Policy = std::function<Affinity(uint32_t workerId)>;

        // all returns an Affinity with all the cores available to the process.
        static Affinity all();

        // allOf returns a Policy that returns affinity for all workers.
        static Policy allOf(const Affinity& affinity);

        // oneOf returns a Policy that returns an affinity with a single enabled core from affinity.
        // The single enabled core in the Policy's returned affinity is:
        //      affinity[workerId % affinity.count()]
        static Policy oneOf(const Affinity& affinity);

        // count returns the number of enabled cores in the affinity.
        size_t count() const;

        // operator[] returns the i'th enabled core from this affinity.
        Core operator[](size_t index) const;

        // add adds the core to this affinity. This affinity is returned to allow for fluent calls.
        Affinity& add(Core);

        Affinity& add(std::initializer_list<Core>); // etc...

        std::vector<Core> mask; // The affinity mask.
    };

    Thread(const Affinity&); // Construct a thread with the given affinity mask.
};
```

As time goes on, I'm increasingly thinking that `marl::Scheduler::setWorkerThreadCount()` and `marl::Scheduler::setThreadInitializer()` were a mistake and should be removed. The mutability of these hurt performance (and currently you still cannot safely call either after you've scheduled work), so I'm thinking we should deprecate them and make a scheduler config structure that's passed to its constructor. This would also provide a sensible place to put the affinity policy:

```c++
class Scheduler {
public:
    using ThreadInitializer = std::function<void(int workerId)>;

    struct Config {
        struct WorkerThread {
            int count = 0;
            ThreadInitializer initializer;
            Thread::Affinity::Policy affinityPolicy = Thread::Affinity::OneOf(Thread::Affinity::All());
        };
        WorkerThread workerThread;
        Allocator* allocator = Allocator::Default;

       // fluent setters can also go in here. For example:
       //     marl::Scheduler scheduler(marl::Scheduler::Config()
       //         .setWorkerThreadCount(2)
       //         .setWorkerThreadInitializer([](int id) { /* ... */ })
       //     );
    };

    Scheduler(const Config&);

    MARL_DEPRECATED("use marl::Scheduler::Config")
    Scheduler(Allocator* allocator = Allocator::Default);

    MARL_DEPRECATED("use marl::Scheduler::Config")
    void setThreadInitializer(const std::function<void()>& init);

    MARL_DEPRECATED("use marl::Scheduler::Config")
    void setWorkerThreadCount(int count);

    ...
};
```

Does this make sense?
If so, does it fit with your needs?

**Comment by magenbluten** [comment]
from my experience "pin"ing alone was only half the work. on linux you might want to  completely skip the worker threads from user space scheduling using `isolcpus=3,5,7,whatever` bootparam and use these threads for your workers ( `oneOf` ). 

but this is certainly application dependent.

+1 to remove bogus `.set*` functions if possible plus sane defaults plus allowing tweaks for advanced usage.

**Comment by ben-clayton** [comment]
@magenbluten - I've put together a draft change for specifying thread affinities based on this discussion in #146.
Does this give you everything you need?

Cheers,
Ben

**Comment by magenbluten** [comment]
Wow! Looks pretty much awesome! Thx!

**Comment by ben-clayton** [comment]
Great, thanks for the very quick response!

**Comment by ben-clayton** [comment]
Done with https://github.com/google/marl/pull/146.
