### ISSUE TITLE
Webassembly compatibility

### ISSUE THREAD

**Issue by Guillaume227** [google/marl#236]
I attempted compiling with emscripten a project that depends on marl and I am hitting an error in osfiber_asm.h.
```marl/src/osfiber_asm.h:40:2: error: "Unsupported target"```

Would anyone have any pointer regarding what it would take to port marl to webasm? Has it been considered/attempted?

**Comment by AWoloszyn** [comment]
My understanding of web assembly is that  it does not yet have full fiber/stack switching support. Marl requires a working makecontext/swapcontext, or the ability to insert oyr item assembly version.

I think emscripten Asyncify might have enough support for marl, as marl does not move fibers between threads once started, but there needs to be some work there to verify and add the bits and pieces that are missing. Otherwise we have to wait until one of the various fiber/coroutine/async/stack switching proposals is finalized and available in webasm and emscripten.

**Comment by Guillaume227** [comment]
Thank you for the informed reply. For my own information, where can I get more information and track those webasm/emscripten proposals?

**Comment by AWoloszyn** [comment]
The different versions of this I have seen are in the following links:

https://github.com/WebAssembly/design/issues/1359
https://github.com/WebAssembly/stack-switching
https://github.com/WebAssembly/stack-switching/blob/main/proposals/fibers/Explainer.md

One note about emscripten/ASYNCIFY is that IIUC it may make compilation time/program size balloon because it has to do a lot of analysis to figure out where fibers might get swapped out, but I am not completely understanding of all of the implications there.

**Comment by Guillaume227** [comment]
Thanks! 
For the time being I managed to get something to run off standard (current version) emscripten, using `emscripten/fiber.h` and ASYNCIFY emscripten link option.

I just opened a PR: #238
I tested on firefox and chrome using the code in `examples/ `
Here is what the `tasks_in_tasks` example looks like in the browser:
http://localhost:8080/tasks_in_tasks.html
![image](https://user-images.githubusercontent.com/9445488/219900265-83cd7a96-edf2-4c6c-9862-85d37d4de5a7.png)

**Comment by ben-clayton** [comment]
https://github.com/google/marl/pull/238 has been merged. Thank you very much for the contribution!

Are we good to close this issue?

**Comment by Guillaume227** [comment]
Thanks for the review - all good from my end.
