### ISSUE TITLE
[Question] effect ParallelFor

### ISSUE THREAD

**Issue by dodoleon** [google/marl#239]
I want to implement a ParallelFor function. This is my implementation. this will take a lot of memory to create task. how could I implement a effect ParallelFor function by marl? just like jobsystem::parallel_for of filament project or taskflow::for_each_index of taskflow project.
```
void ParallelFor(size_t begin, size_t end, size_t inc, std::function<void(size_t)>&& func)
{
    scheduler->bind();
    defer(scheduler->unbind());
    assert((end - begin) / inc > 0);
    marl::WaitGroup wg((end - begin) / inc);
    for (size_t i = begin; i < end; i += inc)
    {
        marl::schedule([](size_t i, marl::WaitGroup wg, const std::function<void(size_t)>& func) {
            defer(wg.done());
            func(i);
        },
                       i, wg, func);
    }
    wg.wait();
}
```

**Comment by ben-clayton** [comment]
Hi @dodoleon ,

What you have written is close to what I would have recommended.
A few comments:
* It looks like you're missing a for-loop around `func(i)` so you process `inc` items, instead of one?
* `std::function` usually has some internal storage for lambda captured values. `[i, wg, &func]{ ... }` might be more memory efficient.
* You'll get better performance if you can hoist the `scheduler->bind();` and unbind to a place that is less frequently called.

> this will take a lot of memory to create task

Have you measured the amount of memory consumed? YMMV, but this hasn't typically been an issue.

**Comment by dodoleon** [comment]
I have an effect practice now， this is my implementation.  
```c++
    void ParallelFor(size_t begin, size_t end, size_t inc, std::function<void(size_t)>&& func)
    {
        scheduler->bind();
        defer(scheduler->unbind());
        const size_t thread_num = scheduler->config().workerThread.count;
        const size_t times = (end - begin + inc - 1) / inc;
        const size_t chit_num = std::min(thread_num, times);
        const size_t chip_inc = (times + chit_num - 1) / chit_num * inc;

        marl::WaitGroup wg(static_cast<uint32_t>(chit_num));
        for (size_t chip_i = 0; chip_i < chit_num; ++chip_i)
        {
            marl::schedule([begin, end, inc, chip_inc, chip_i, wg, &func] {
                defer(wg.done());
                size_t b = begin + chip_i * chip_inc;
                size_t e = begin + chip_i * chip_inc + chip_inc;
                for (size_t i = b; i < e; i += inc)
                {
                    if (i < end)
                    {
                        func(i);
                    }
                }
            });
        }
        wg.wait();
    }
```
