### ISSUE TITLE
Implement an Event synchronization primitive

### ISSUE THREAD

**Issue by ben-clayton** [google/marl#46]
Likely interface:

```c++
// Event is a synchronization primitive used to block until a signal is raised.
class Event {
public:
	enum class ClearMode
	{
		// The event signal will be automatically reset when a call to wait()
		// returns.
		// A single call to signal() will only unblock a single (possibly
		// future) call to wait().
		Auto,

		// While the event is in the signaled state, any calls to wait() will
		// unblock without automatically reseting the signaled state.
		// The signaled state can be reset with a call to clear().
		Manual
	};

	Event(ClearMode mode = ClearMode::Auto, bool initialState = false);

	// signal() signals the event, possibly unblocking a call to wait().
	void signal();

	// clear() clears the signaled state.
	void clear();

	// wait() blocks until the event is signaled.
	// If the event was constructed with the Auto ClearMode, then only one 
	// call to wait() will unblock before returning, upon which the signalled state
	// will be automatically cleared.
	void wait();

	// test() returns true if the event is signaled, otherwise false.
	// If the event is signalled and was constructed with the Auto ClearMode
	// then the signalled state will be automatically cleared upon returning.
	bool test();

	// isSignalled() returns true if the event is signaled, otherwise false.
	// Unlike test() the signal is not automatically cleared when the event was 
	// constructed with the Auto ClearMode.
	// Note: No lock is held after bool() returns, so the event state may
	// immediately change after returning. Use with caution.
	bool isSignalled();
}
```

**Comment by digit-google** [comment]
Interesting :) All of the following are nits, so don't take them too seriously:

I suggest clarifying the relationship between wait() and signal(), i.e.:

- The ClearMode::Auto documentation states that "a single call to signal() will only unblock a single call to wait()"

- The signal() documentation states "signal() signals the event, unblocking *any* calls to wait()"

This seems contradictory :-/

Do you want signal() + signalAll(), and also do you want tryWait() as well to auto-reset on success atomically?

It also may be better to use either "event condition" or "event signal", but not both of them, in the description, since this is easily distracting.

Also "signal() signals the event" and "wait() blocks until the event signal is set to true" is not very consistent, i.e. "wait() blocks until the event is signaled", would be clearer.

**Comment by ben-clayton** [comment]
Thanks for the feedback @digit-google. I've tried to incorporate your suggestions back into the original proposal's text.

> Do you want signal() + signalAll()

`signalAll()` is an interesting idea, but adds a certain amount of complexity to the API. It doesn't really make sense in the `ClearMode::Manual` case. If it's something we want, perhaps I should split the class in two.

`tryWait()` is also an interesting idea (although I'm not sure about the name). Is this something you'd need to migrate your hand-rolled SwiftShader code over to this?

**Comment by digit-google** [comment]
I use a tryWait() in my implementation of Vulkan external semaphores in order to have to call marl::blocking_call() when it is not strictly necessary. Granted, this is not using a marl::Event at all, but this allows saving 28 us (i.e. around 30k CPU cycles, and that's on desktop Linux, probably worse on mobile) when the semaphore is already signaled on wait.

On the other hand, the value of operator bool() seems to be nil unless you can guarantee that no other thread (but not fiber) is actually trying to access the event. Maybe useful in a trivial unit-test, but this is subtle (and thus dangerous) enough that it warrants a comment that makes it clearer (Alternatively, Chromium tends to name these kind of methods as "getFlagForTesting()" to make it clear that this is only for unit-tests).

On the other hand, tryWait() has no non-trivial behaviour, i.e. behaves atomically every time.

**Comment by ben-clayton** [comment]
Updated the proposal with `test()` and changed the `bool` operator to `isSignalled()` with additional warnings.

> On the other hand, the value of operator bool() seems to be nil unless you can guarantee that no other thread (but not fiber) is actually trying to access the event. 

This API is derived from the [sw::Event class](https://swiftshader.googlesource.com/SwiftShader/+/refs/heads/master/src/System/Synchronization.hpp#122) I originally wrote for SwiftShader. The `operator bool()` was used exclusively for `ASSERT()` sanity checks, checking that at certain states the event should be either signalled or not.

Please let me know what you think.
